<?php
namespace Eden\Utility;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    public function testCollection()
    {
		$class = eden('utility')->collection();
		$this->assertInstanceOf('Eden\\Utility\\Collection', $class);
    }

    public function testCookie()
    {
		$class = eden('utility')->cookie();
		$this->assertInstanceOf('Eden\\Utility\\Cookie', $class);
    }

    public function testCurl()
    {
		$class = eden('utility')->curl();
		$this->assertInstanceOf('Eden\\Utility\\Curl', $class);
    }

    public function testFile()
    {
		$class = eden('utility')->file('/some/file');
		$this->assertInstanceOf('Eden\\Utility\\File', $class);
    }

    public function testFolder()
    {
		$class = eden('utility')->folder('/some/folder');
		$this->assertInstanceOf('Eden\\Utility\\Folder', $class);
    }

    public function testImage()
    {
		$class = eden('utility')->image(realpath(__DIR__.'/../../../assets/stars.gif'), 'gif');
		$this->assertInstanceOf('Eden\\Utility\\Image', $class);
    }

    public function testLanguage()
    {
		$class = eden('utility')->language();
		$this->assertInstanceOf('Eden\\Utility\\Language', $class);
    }

    public function testModel()
    {
		$class = eden('utility')->model();
		$this->assertInstanceOf('Eden\\Utility\\Model', $class);
    }

    public function testOauth()
    {
		$class = eden('utility')->oauth();
		$this->assertInstanceOf('Eden\\Utility\\Oauth', $class);
    }

    public function testOauth2()
    {
		$class = eden('utility')->oauth2();
		$this->assertInstanceOf('Eden\\Utility\\Oauth2', $class);
    }

    public function testPath()
    {
		$class = eden('utility')->path('/some/path');
		$this->assertInstanceOf('Eden\\Utility\\Path', $class);
    }

    public function testSession()
    {
		$class = eden('utility')->session();
		$this->assertInstanceOf('Eden\\Utility\\Session', $class);
    }

    public function testTemplate()
    {
		$class = eden('utility')->template();
		$this->assertInstanceOf('Eden\\Utility\\Template', $class);
    }

    public function testTimezone()
    {
		$class = eden('utility')->timezone('America/Los_Angeles');
		$this->assertInstanceOf('Eden\\Utility\\Timezone', $class);
    }

    public function testType()
    {
		$class = eden('utility')->type();
		$this->assertInstanceOf('Eden\\Utility\\Type', $class);
		
		$class = eden('utility')->type('something');
		$this->assertInstanceOf('Eden\\Utility\\Type\\StringType', $class);
		
		$class = eden('utility')->type(1, 2, 3);
		$this->assertInstanceOf('Eden\\Utility\\Type\\ArrayType', $class);
    }

    public function testValidation()
    {
		$class = eden('utility')->validation('test');
		$this->assertInstanceOf('Eden\\Utility\\Validation', $class);
    }
}
